// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hehmuleizhrxslgplptj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlaG11bGVpemhyeHNsZ3BscHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzODYzMjAsImV4cCI6MjA3ODk2MjMyMH0.pg0pkERAAnsBt5FzEFOjxaRcgDHH0LpT4TnWJ6K-N-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});